2025-03-26 18:11:38,701 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C05D2590>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:39,685 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C05FFD90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:40,708 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C061EDD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:41,737 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C06378D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:42,757 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0637AD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:43,864 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0655ED0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:44,898 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0657510>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:45,980 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0664B10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:47,069 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0665E10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:48,164 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0663590>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:49,167 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C05D0090>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:50,164 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C064D950>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:51,235 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C064E710>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:48,248 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F67126090>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:49,278 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F67127550>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:50,313 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F671685D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:51,356 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F6717BC50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:51,744 - INFO - Sistema encerrado
2025-03-27 20:27:31,264 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9B6D190>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:32,231 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9B8BE90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:33,340 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BAA8D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:34,380 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BB7C50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:35,468 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BC13D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:36,526 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BD2550>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:37,634 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BD3B50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:38,645 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BE4750>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:39,752 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BE5850>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:40,748 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BDE6D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:41,758 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BC1050>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:42,777 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BEBC50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:43,898 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BD3810>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:44,928 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BE1E10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:45,925 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BDD890>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:46,969 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BEEBD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:48,054 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BF5D50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:49,079 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BFAC90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:50,105 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BE1B90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:51,229 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BFD3D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:52,258 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9BFE6D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:53,285 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C03210>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:54,306 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C03E90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:55,369 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C08D10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:56,385 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C09BD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:57,439 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C0EC90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:58,589 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C0FF50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:27:59,587 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C14FD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:00,646 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C15F50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:01,766 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C19210>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:02,798 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C1B610>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:03,860 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C24B10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:04,836 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C26150>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:05,891 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C23110>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:06,939 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C287D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:07,938 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C2D890>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:09,070 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C2EE90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:10,115 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C33E90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:11,069 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C3D4D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:12,189 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C3A850>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:13,202 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C3B850>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:14,243 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C48CD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:15,250 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C4A090>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:16,278 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C47090>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:17,380 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C4C690>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:18,407 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C51690>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:19,435 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202F9C52E90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-27 20:28:19,666 - INFO - Sistema encerrado
