2025-03-26 18:11:38,701 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C05D2590>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:39,685 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C05FFD90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:40,708 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C061EDD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:41,737 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C06378D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:42,757 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0637AD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:43,864 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0655ED0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:44,898 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0657510>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:45,980 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0664B10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:47,069 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0665E10>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:48,164 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C0663590>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:49,167 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C05D0090>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:50,164 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C064D950>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:11:51,235 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000288C064E710>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:48,248 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F67126090>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:49,278 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F67127550>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:50,313 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F671685D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:51,356 - ERROR - [DASHBOARD] Falha na conexão: HTTPConnectionPool(host='localhost', port=3310): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F6717BC50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))
2025-03-26 18:15:51,744 - INFO - Sistema encerrado
